"""
make_version.py - Bake the latest NEWS version into src/app_version.py.

The Android About dialog cannot read NEWS at runtime (NEWS is not packaged into
the APK), so write the latest NEWS version (e.g. "v20260608") into a small
bundled module the app can import. The desktop still reads NEWS directly. Re-run
after editing NEWS (and then assets/make_presplash.py to match the splash):

    python assets/make_version.py
"""

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, os.path.join(_ROOT, "src"))

from ui_util import latest_news_version  # noqa: E402  (after sys.path setup)


def main() -> None:
    """Read NEWS and (over)write src/app_version.py with its latest version."""
    with open(os.path.join(_ROOT, "NEWS"), encoding="utf-8") as fh:
        version = latest_news_version(fh.read()) or "v1.0.0"
    out = os.path.join(_ROOT, "src", "app_version.py")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write('"""Generated by assets/make_version.py from NEWS. '
                 'Do not edit by hand."""\n\n')
        fh.write(f'VERSION = "{version}"\n')
    print(f"wrote {out} (VERSION = {version})")


if __name__ == "__main__":
    main()
